form_django/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('music.urls')),
    path('admin/', admin.site.urls),
]

form_django/demo/music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('', views.index, name='home'),
    path('add/', views.addMusic, name='addMusic'),
    path('save/', views.saveMusic, name='saveMusic'),
    path('list/', views.listMusic, name='listMusic'),
    path('name/', views.nameSinger, name='nameSinger'),
]

form_django/demo/music/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Music(models.Model):
    nameSong = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    created_at = models.DateTimeField(
        default=timezone.datetime.now, widget=models.TextInput(attrs={'class': 'create-at'}))


# class Singers(models.Model):
#     nameSong = models.CharField(max_length=100)
#     nameSinger = models.CharField(max_length=50)

form_django/demo/music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .form import MusicForm, Names
from .models import Music

# Create your views here.


def index(request):
    return HttpResponse("Page MUSIC")


def addMusic(request):
    add = MusicForm()
    return render(request, 'music/addmusic.html', {'add': add})


def saveMusic(request):
    if request.method == "POST":
        q = MusicForm(request.POST)
        if q.is_valid():
            q.save()
            return HttpResponse("Add Music Success")
        else:
            return HttpResponse("Not Validated")
    else:
        return HttpResponse("Method Not Allowed")


def listMusic(request):
    listMusic = Music.objects.all()
    list = {
        "list": listMusic
    }
    return render(request, 'music/listmusic.html', list)

# def updateMusic(request, musicId):


def nameSinger(request):
    name = Names()
    context = {"name": name}
    return render(request, 'music/nameSinger.html', context)

form_django/demo/music/templates/music/addmusic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>App Music ThiệnHi</title>
</head>
<body>
    <form action="{% url 'music:saveMusic' %}" method="post">
        {% csrf_token %}
        <h3>Music</h3>
        {{add.nameSong}}
        <h3>Content</h3>
        {{add.content}}
        <h3>Created at</h3>
        <input type="datetime-local" value="">
        {{add.created_at}}
        <!-- <input type="datetime-local" value="{{add.created_at}}"> -->
        <button type="submit" value="Add" >
    </form>
</body>
</html>

form_django/demo/music/templates/music/listmusic.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <h1>List Music</h1>
        {% if list %}
            <div class="list-music" >
                {%  for song in list%}
                    <h4 style="color: red; font-size:15px;">{{song.id}}, {{song.nameSong}} -- {{song.content}}</h4>
                    <!-- <h3></h3> -->
                    <h4></h4>
                    <p style="color: violet; font-size:15px;">{{song.created_at}}</p>
                {% endfor %}
            </div>
            <button type="submit" style="color: gold; background-color:cyan;">Back</button>
        {% endif %}
</body>
</html>

form_django/demo/music/templates/music/nameSinger.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title> -->
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{name}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>