my_project/project_django/images/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.image, name="Image")
]

my_project/project_django/project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('image/', include("images.urls")),
    path("", include("sports.urls")),
    path('admin/', admin.site.urls),
]

my_project/project_django/sports/urls.py
from django.urls import path
from . import views

app_name = 'sport'
urlpatterns = [
    path("<int:question_id>/", views.vote, name="vote"),
    path("answer/<int:question_id>", views.answer, name="answer"),
    path("list/", views.listQuestions, name="listQuestions"),
    path("", views.hello, name="Hello")
]

my_project/project_django/images/models.py
from django.db import models

# Create your models here.

my_project/project_django/sports/models.py
from django.db import models

# Create your models here.


class questionSports(models.Model):
    questions = models.CharField(max_length=250)
    time_public = models.DateTimeField()


class choicesQuestion(models.Model):
    questions = models.ForeignKey(questionSports, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

my_project/project_django/images/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

url = 'https://bloggame.net/uploads/worigin/2020/03/28/Hinhnendautruongchanlydepnhat15e7eccb8dbb4f_5abfbc798434fbe082a09236905b14df.jpg'


def image(response):
    return HttpResponse('< img src={%url%}/>')

my_project/project_django/sports/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import questionSports, choicesQuestion

# Create your views here.


def hello(request):
    name = "Thiện Kim"
    idol = ["Cristiano Ronaldo", "Thiện Hi", "CR7"]
    context = {"name": name, "idol": idol}
    return render(request, "sports/index.html", context)


def listQuestions(request):
    list = questionSports.objects.all()
    answer = choicesQuestion.objects.all()
    context = {"list": list, "answer": answer}
    return render(request, "sports/list_question.html", context)


def answer(request, question_id):
    q = questionSports.objects.get(pk=question_id)
    context = {"answer": q}
    return render(request, "sports/answer.html", context)


def vote(request, question_id):
    q = questionSports.objects.get(pk=question_id)
    try:
        data = request.POST["choice"]
        c = q.choicesquestion_set.get(pk=data)
    except:
        HttpResponse("Error exits data")
    c.vote = c.vote + 1
    c.save()
    return render(request, "sports/vote.html", {"vote": q})

my_project/project_django/sports/templates/sports/answer.html
{% extends 'sports/stastic.html' %}

{% block content%}

    {% if answer %}
        {{answer.questions}}
        <form action="{% url 'sport:vote' answer.id %}" class="form-answer" method="post">
            {% csrf_token %}
            <!-- <ul> -->
                {% for item in answer.choicesquestion_set.all %}
                    <input type="radio" name="choice" value="{{item.id}}"style="color: rgb(179, 26, 240);" >
                        {{ item.choice_text}}
                    </input>
                    <br/>
                {% endfor %}
                <input type="submit" />
            <!-- </ul> -->
        </form>
    {% endif %}

{% endblock %}

my_project/project_django/sports/templates/sports/index.html
{% extends 'sports/stastic.html' %}
{% block content %}
    <h1>Đây là <u>{{ name }}</u>,chào mừng bạn đến với Django</h1>
    <img width="900" height="500" src="https://bloggame.net/uploads/worigin/2020/03/28/Hinhnendautruongchanlydepnhat15e7eccb8dbb4f_5abfbc798434fbe082a09236905b14df.jpg" / >
    <p>My Idol:</p>
    <ul>
        {% for item in idol %}
            {% if item != "Thiện Hi" %}
                <li>{{ item }}</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

my_project/project_django/sports/templates/sports/list_question.html
{% extends 'sports/stastic.html' %}

{% block content%}

    {% if list %}
        {% for item in list %}
            <a href="{% url 'sport:answer' item.id %}"><p style="color: rgb(179, 26, 240);" >{{ item.questions}}</p></a>
        {% endfor %}
    {% else %}
        <p style="color:red;" >Đéo có dữ liệu</p>
    {% endif %}

{% endblock %}

my_project/project_django/sports/templates/sports/stastic.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>ThienHi</title>
    <link rel="stylesheet" href="{% static 'sports/index.css' %}" >
</head>
<body>
    <div class="header">
        <h1>My Content</h1>
    </div>
    <div class="menu">
        <h1>Menu link</h1>
        <ul>
            <button><a href="{% url 'sport:listQuestions' %}">Vote</a></button>
            <li><a href="https://www.facebook.com/Cristiano/">Cr7</a></li>
            <li><a href="https://www.facebook.com/namblue">Nam Blue</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100013919736220">ThienHi</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content%}
        {% endblock %}
    </div>
</body>
</html>

my_project/project_django/sports/templates/sports/vote.html
{% extends 'sports/stastic.html' %}

{% block content%}
    {% if vote %}
        <h1>{{vote.questions}}</h1>
        <p>Vote</p>
        {% for item in vote.choicesquestion_set.all %}
            <p>{{item.choice_text}} : {{item.vote}}</p>
        {% endfor %}
    {% endif %}
    <button><a href="{% url 'sport:Hello' %}">Back Home</a></button>
{% endblock %}